<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="1.0" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="7.40" /> <!-- Link 1 -->
  <xacro:property name="height2" value="2" /> <!-- Link 2 -->
  <xacro:property name="height3" value="2" /> <!-- Link 3 -->
  <xacro:property name="elbow_width" value="1.0" /> <!-- The length of elbow -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="limit_lower" value="-1.57" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="limit_upper" value="1.57" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="limit_effort" value="30" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="limit_velocity" value="30" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="scale" value="0.4" />
  <xacro:property name="y_offset" value="0.14" />
  <xacro:property name="x_offset" value="0.10" />
  <xacro:property name="z_offset" value="0.10" />
  <xacro:property name="leftArm_offset" value="2.5" />
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find arm_description)/urdf/arm.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find arm_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="1.1 -3.15 8" rpy="-1.57 0 1.57"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/body.STL" scale="${scale+0.1} ${scale+0.1} ${scale+0.1}"/>
	<!--box size="${width} ${width} ${height1}"/-->
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="1000"/>
      <inertia
	  ixx="990.0" ixy="0.0" ixz="0.0"
	  iyy="990.0" iyz="0.0"
	  izz="990.0"/>
    </inertial>
  </link>

  <joint name="elbow1_1" type="continuous">
    <parent link="link1"/>
    <child link="elbow1"/>
    <origin xyz="${x_offset} ${width/2} ${height1-elbow_width/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="${limit_effort}" lower="${limit_lower}" upper="${limit_upper}" velocity="${limit_velocity}" />
    <safety_controller k_velocity="100" k_position="15" soft_lower_limit="-1.9" soft_upper_limit="0.5" />
  </joint>

  <!-- Elbow 1 Link -->
  <link name="elbow1">
    <collision>
      <origin xyz="0 ${elbow_width/2} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/2} 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/shoulder_ball.STL" scale="0.4 0.4 0.4"/>
	<!--box size="${elbow_width} ${elbow_width} ${elbow_width}"/-->
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 ${elbow_width/2} 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>

  <joint name="elbow1_2" type="continuous">
    <parent link="elbow1"/>
    <child link="link2"/>
    <origin xyz="0 ${elbow_width/2+0.04} ${-elbow_width*0}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${-height2/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/2.7} ${-y_offset-0.4} ${height2/3.5}" rpy="-1.57 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/shoulder_link.STL" scale="0.4 0.4 0.4"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-height2/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="10.1" ixy="0.0" ixz="0.0"
	  iyy="10.1" iyz="0.0"
	  izz="10.1"/>
    </inertial>
  </link>

  <joint name="elbow2_1" type="continuous">
    <parent link="link2"/>
    <child link="elbow2"/>
    <origin xyz="0 0 ${-height2-z_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="${limit_effort}" lower="${limit_lower}" upper="${limit_upper}" velocity="${limit_velocity}" />
    <safety_controller k_velocity="100" k_position="15" soft_lower_limit="-1.9" soft_upper_limit="0.5" />

  </joint>

  <!-- Elbow 2 Link -->
  <link name="elbow2">
    <collision>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/2.5} ${-elbow_width/4-y_offset} ${z_offset-0.08}" rpy="-1.57 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/elbow_ball.STL" scale="${scale} ${scale} ${scale}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>

  <joint name="elbow2_2" type="continuous">
    <parent link="elbow2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Forearm Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${-height3/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/4.1} ${-elbow_width/4-y_offset} ${z_offset+0.3}" rpy="-1.57 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/forearm_link.STL" scale="${scale} ${scale} ${scale}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-height3/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="3.1" ixy="0.0" ixz="0.0"
	  iyy="3.1" iyz="0.0"
	  izz="3.1"/>
    </inertial>
  </link>

  <joint name="elbow3_1" type="continuous">
    <parent link="link3"/>
    <child link="elbow3"/>
    <origin xyz="0 ${0.15-y_offset} ${-1.79+z_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Elbow 3 Link -->
  <link name="elbow3">
    <collision>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/5.5} ${-0.15-elbow_width/4.5} ${elbow_width/1.47}" rpy="0 3.14 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/hand_assem.STL" scale="${scale} ${scale} ${scale}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>











  <joint name="left_elbow1_1" type="continuous">
    <parent link="link1"/>
    <child link="left_elbow1"/>
    <origin xyz="${x_offset} ${-width/2-leftArm_offset} ${height1-elbow_width/2}" rpy="0 0 3.14"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="${limit_effort}" lower="${limit_lower}" upper="${limit_upper}" velocity="${limit_velocity}" />
    <safety_controller k_velocity="100" k_position="15" soft_lower_limit="-1.9" soft_upper_limit="0.5" />
  </joint>

  <link name="left_elbow1">
    <collision>
      <origin xyz="0 ${elbow_width/2} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/2} 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/shoulder_ball.STL" scale="0.4 0.4 0.4"/>
	<!--box size="${elbow_width} ${elbow_width} ${elbow_width}"/-->
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 ${elbow_width/2} 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>

  <joint name="left_elbow1_2" type="continuous">
    <parent link="left_elbow1"/>
    <child link="left_link2"/>
    <origin xyz="0 ${elbow_width/2+0.04} ${-elbow_width*0}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="left_link2">
    <collision>
      <origin xyz="0 0 ${-height2/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/2.7} ${-y_offset-0.4} ${height2/3.5}" rpy="-1.57 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/shoulder_link.STL" scale="0.4 0.4 0.4"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-height2/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="10.1" ixy="0.0" ixz="0.0"
	  iyy="10.1" iyz="0.0"
	  izz="10.1"/>
    </inertial>
  </link>

  <joint name="left_elbow2_1" type="continuous">
    <parent link="left_link2"/>
    <child link="left_elbow2"/>
    <origin xyz="0 0 ${-height2-z_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="${limit_effort}" lower="${limit_lower}" upper="${limit_upper}" velocity="${limit_velocity}" />
    <safety_controller k_velocity="100" k_position="15" soft_lower_limit="-1.9" soft_upper_limit="0.5" />

  </joint>

  <!-- Elbow 2 Link -->
  <link name="left_elbow2">
    <collision>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/2.5} ${-elbow_width/4-y_offset} ${z_offset-0.08}" rpy="-1.57 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/elbow_ball.STL" scale="${scale} ${scale} ${scale}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>

  <joint name="left_elbow2_2" type="continuous">
    <parent link="left_elbow2"/>
    <child link="left_link3"/>
    <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Forearm Link -->
  <link name="left_link3">
    <collision>
      <origin xyz="0 0 ${-height3/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-elbow_width/4.1} ${-elbow_width/4-y_offset} ${z_offset+0.3}" rpy="-1.57 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/forearm_link.STL" scale="${scale} ${scale} ${scale}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-height3/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="3.1" ixy="0.0" ixz="0.0"
	  iyy="3.1" iyz="0.0"
	  izz="3.1"/>
    </inertial>
  </link>

  <joint name="left_elbow3_1" type="continuous">
    <parent link="left_link3"/>
    <child link="left_elbow3"/>
    <origin xyz="0 ${0.15-y_offset} ${-1.79+z_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Hand Link -->
  <link name="left_elbow3">
    <collision>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${elbow_width/3.5} ${-elbow_width/2.7} ${-elbow_width/1.37}" rpy="0 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/hand_assem_left.STL" scale="${scale} ${scale} ${scale}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
  </link>







  <transmission name="tran_elbow1_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow1_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_elbow1_2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow1_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_elbow2_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow2_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_elbow2_2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow2_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_elbow3_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow3_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  
 <transmission name="left_tran_elbow1_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_elbow1_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_motor1_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_tran_elbow1_2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_elbow1_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_motor1_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_tran_elbow2_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_elbow2_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_motor2_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_tran_elbow2_2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_elbow2_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_motor2_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_tran_elbow3_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_elbow3_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_motor3_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>






</robot>
