<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="1.0" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="9" /> <!-- Link 1 -->
  <xacro:property name="height2" value="2" /> <!-- Link 2 -->
  <xacro:property name="height3" value="2" /> <!-- Link 3 -->
  <xacro:property name="elbow_width" value="1.0" /> <!-- The length of elbow -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find arm_description)/urdf/arm.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find arm_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${width*2.0} 0.5 0" rpy="1.57 0 -1.57"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/dummyBody.STL" scale="2 2.6 2"/>
	<!--box size="${width} ${width} ${height1}"/-->
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="3.0" ixy="0.0" ixz="0.0"
	  iyy="3.0" iyz="0.0"
	  izz="3.0"/>
    </inertial>
  </link>

  <joint name="elbow1_1" type="continuous">
    <parent link="link1"/>
    <child link="elbow1"/>
    <origin xyz="0 ${width/2} ${height1-elbow_width/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Elbow 1 Link -->
  <link name="elbow1">
    <collision>
      <origin xyz="0 ${elbow_width/2} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${elbow_width/2.39} 0 ${elbow_width/2-0.13}" rpy="-1.57 1.57 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/gearBox.STL" scale="0.2 0.2 0.2"/>
	<!--box size="${elbow_width} ${elbow_width} ${elbow_width}"/-->
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 ${elbow_width/2} 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="elbow1_2" type="continuous">
    <parent link="elbow1"/>
    <child link="link2"/>
    <origin xyz="0 ${elbow_width/2} ${-elbow_width*0}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${-height2/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-width/2.3} 0 ${-height2/1}" rpy="1.57 0 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/armSkeleton.STL" scale="0.2 0.26 0.2"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-height2/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="elbow2_1" type="continuous">
    <parent link="link2"/>
    <child link="elbow2"/>
    <origin xyz="0 0 ${-height2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Elbow 2 Link -->
  <link name="elbow2">
    <collision>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-elbow_width/1.3} 0" rpy="0 3.14 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/gearBox.STL" scale="0.2 0.2 0.2"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="elbow2_2" type="continuous">
    <parent link="elbow2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${-elbow_width}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Palm Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${-height3/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${-height3/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-height3/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="elbow3_1" type="continuous">
    <parent link="link3"/>
    <child link="elbow3"/>
    <origin xyz="0 0 ${-height3}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Elbow 3 Link -->
  <link name="elbow3">
    <collision>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${elbow_width} ${elbow_width} ${elbow_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="-1.57 1.57 0"/>
      <geometry>
	<mesh filename="package://arm_description/meshes/gearBox.STL" scale="0.2 0.2 0.2"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-elbow_width/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>


  <transmission name="tran_elbow1_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow1_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_elbow1_2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow1_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_elbow2_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow2_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_elbow2_2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow2_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_elbow3_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow3_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>
